version: '3'

services:
  database:
    image: mysql
    container_name: db_docker_symfony
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      dev:
    volumes:
      - "/srv/dev-disk-by-uuid-70b38318-03df-4998-8205-a38f788b0005/R51/WebSite/mysql:/var/lib/mysql"

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_docker_symfony
    restart: unless-stopped
    depends_on:
      - database
    ports:
      - 8181:80
    environment:
      PMA_HOST: database
    networks:
      dev:

  www:
    image: php:7.4-apache
    container_name: www_docker_symfony
    ports:
      - "8741:80"
    volumes:
      - "/srv/dev-disk-by-uuid-70b38318-03df-4998-8205-a38f788b0005/R51/WebSite/php:/etc/apache2/sites-enabled"
      - "/srv/dev-disk-by-uuid-70b38318-03df-4998-8205-a38f788b0005/R51/WebSite/www:/var/www"
    restart: unless-stopped
    networks:
      - dev

networks:
  dev:

volumes:
  db-data:
